---
on:
  pull_request: &ignore-paths
    paths-ignore:
      - ".gitattributes"
      - ".gitignore"
      - "CHANGELOG.md"
      - "docs/**"
      - "README.md"

  push: *ignore-paths

name: Composer require checker

permissions:
  contents: read

jobs:
  composer-require-checker:
    uses: yiisoft/yii2-actions/.github/workflows/composer-require-checker.yml@161a59a5e7d9c5b650c4a132f6e9292bacfcb5cc
