---
on:
  pull_request: &ignore-paths
    paths-ignore:
      - ".gitattributes"
      - ".gitignore"
      - "CHANGELOG.md"
      - "docs/**"
      - "README.md"

  push: *ignore-paths

name: ecs

permissions:
  contents: read

jobs:
  easy-coding-standard:
    uses: yiisoft/yii2-actions/.github/workflows/ecs.yml@161a59a5e7d9c5b650c4a132f6e9292bacfcb5cc
    with:
      php-version: '["8.3"]'
